### PR TITLE
fix: allow page to have small widths on mobile

### PR DESCRIPTION
**Pull request by jryans**
This tweaks the width constraint so that smaller screens can wrap the page content to match the screen width.

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Thanks!

**Comment by jryans** [comment]
Thanks! Forgot about the commit style, I'll re-read the PR guide next time. 😅

**Comment by magnus-madsen** [comment]
No worries!

**Comment by magnus-madsen** [comment]
This will be live next time I manually update the site.

**Pull request merged**
